### PR TITLE
Add facetime call support

### PR DESCRIPTION
**Pull request by victorcerutti**
Hello,
This is my first PR, I hope everything is done right

I wanted to add the support of calling someone on facetime.
I use it to call myself when I want to have a look on my home from afar but it can also be used to call anyone else from any automation.

To be able to work, you have to whitelist "System Events" in the Security > Accessibility preferences panel of macOS. A prompt will probably lead the user to the panel the first time the script is tried. I don't know if it's worth mentioning in the doc.

### CODE REVIEW

**Comment by maddox** [comment]
Hi! So sorry for ignoring this for so long. Some how I wasn't watching my own repo and didn't get a notification of these pulls of yours.

I love this idea, but I'm concerned that having a way to remotely turn on your camera is a huge scary idea. While it's not a great idea to have any of this exposed externally, even if you did, the effects are benign. 

I wonder if we should add authentication to the API first before we add this.

**Comment by technicalpickles** [comment]
> To be able to work, you have to whitelist "System Events" in the Security > Accessibility preferences panel of macOS. A prompt will probably lead the user to the panel the first time the script is tried. I don't know if it's worth mentioning in the doc.

Seems like it'd be worth mentioning, since it could trip users up if they miss it the first time.

> i'm concerned that having a way to remotely turn on your camera is a huge scary idea.

Maybe facetime could be enabled via the config.json?

> I wonder if we should add authentication to the API first before we add this.

Also probably good 😅

**Comment by victorcerutti** [comment]
I think too that authentification is a must have (either ip whitelisting of http/header password)
Also, if the number of endpoints is growing, it could be a good idea to have them disabled by default and enable them according to your need

**Comment by maddox** [comment]
I'm going to close this since I don't love the security issues. Remotely turning on the camera with a simple `POST` isn't something I want this project to be responsible for, heh. 

Maybe one day if there's password support and less surface area for people to shoot themselves in the foot we could add it. Thanks!

**Pull request closed without merging**
